// Generated by Nuxt Auto Form

import type { ButtonProps, InferInput } from '@nuxt/ui'
import type { ConcreteComponent } from '@vue/runtime-core'

export type AutoFormState<TSchema> = Partial<InferInput<TSchema>>

export type ComponentsMap = Record<string, (params: { key: string, state: any, zodType: any, config: AutoFormConfig }) => ComponentDefinition | null>

export interface AutoFormConfig {
  /** Submit button configuration */
  submit?: {
    /** Name of the globally defined component to use as the submit button */
    component: ConcreteComponent | string
    /** Props to pass to the custom submit button */
    props?: Record<string, any>
  } | {
    component?: undefined
    /** Props to pass to the Nuxt UI `UButton` component */
    props?: ButtonProps
  } | false

  /** AutoFormModal default button labels */
  modal?: {
    /** Default label for the submit button. @default 'Submit' */
    submitLabel?: string
    /** Default label for the cancel/close button. @default 'Cancel' */
    closeLabel?: string
  }

  /**
   * Customize default form styles
   */
  theme?: {
    /**
     * Apply `w-full` class to all input components by default.
     * @default true
     */
    wFull?: boolean
    /**
     * Generate default labels from field names globally. Set to `false` to disable auto-generated labels.
     * Manually set titles via `meta().title` will still render regardless of this setting.
     * @default true
     */
    enableDefaultTitles?: boolean
  }

  /**
   * Customize the default components used for rendering form fields.
   *
   * @example
   * ```ts
   * components: {
   *   email: () => ({ component: UInput, componentProps: { type: 'email' } }),
   * }
   * ```
   */
  components?: ComponentsMap

  /**
   * Custom meta string preprocessors that transform prefixed strings in `meta()`.
   * The `$` prefix and `:` suffix are added automatically to keys.
   *
   * @example
   * ```ts
   * metaStringProcessors: {
   *   upper: value => value.toUpperCase(),
   *   slug: value => value.trim().toLowerCase().replace(/\s+/g, '-'),
   * }
   * ```
   *
   * @see https://nuxt-auto-form.norbiros.dev/customization/preprocessors
   */
  metaStringProcessors?: Record<string, (value: string, context: {
    key: string
    path: string
    meta: Record<string, any>
    config: AutoFormConfig
  }) => any>
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Configuration related to `@norbiros/nuxt-auto-form` Nuxt module */
    autoForm?: AutoFormConfig | undefined
  }

  interface AppConfig {
    /** Configuration related to `@norbiros/nuxt-auto-form` Nuxt module */
    autoForm?: AutoFormConfig | undefined
  }
}

export {}
