// Generated by Nuxt Auto Form

import type { ButtonProps } from '@nuxt/ui'
import type { ConcreteComponent } from '@vue/runtime-core'

export type ComponentsMap = Record<string, (key: string, zodType: any) => ComponentDefinition | null>

export interface AutoFormConfig {
  /** Submit button configuration */
  submit?: {
    /** Name of the globally defined component to use as the submit button */
    component: ConcreteComponent | string
    /** Props to pass to the custom submit button */
    props?: Record<string, any>
  } | {
    component?: undefined
    /** Props to pass to the Nuxt UI `UButton` component */
    props?: ButtonProps
  }
  /**
   * Customize the default components used for rendering form fields.
   *
   * @example
   * ```ts
   * components: {
   *   email: () => ({ component: UInput, componentProps: { type: 'email' } }),
   * }
   * ```
   */
  components?: ComponentsMap
}

declare module 'nuxt/schema' {
  interface AppConfigInput {
    /** Configuration related to `@norbiros/nuxt-auto-form` Nuxt module */
    autoForm?: AutoFormConfig | undefined
  }

  interface AppConfig {
    /** Configuration related to `@norbiros/nuxt-auto-form` Nuxt module */
    autoForm?: AutoFormConfig | undefined
  }
}

export {}
