// Generated by Nuxt Auto Form

declare module 'zod' {
  interface GlobalMeta {
    /** Configuration related to `nuxt-auto-form` Nuxt module */
    autoForm?: {
      /** Float input box to the right of the label */
      floatRight?: boolean
    }
  }
}

export {}
