shellEmulator: true

trustPolicy: no-downgrade
trustPolicyExclude:
  - semver@6.3.1

packages:
  - ./
  - playground
  - docs/

ignoredBuiltDependencies:
  - sharp

onlyBuiltDependencies:
  - better-sqlite3
